import { GithubUser, RepoSearch, UserSearch } from "../GitHubType"

export const GithubUserMock: GithubUser = {
    login: 'valmojr',
    id: 0,
    node_id: 'teste',
    avatar_url: 'https://avatars.githubusercontent.com/u/70849974?v=4',
    gravatar_id: 'teste',
    url: 'teste',
    html_url: 'teste',
    followers_url: 'teste',
    following_url: 'teste',
    gists_url: 'teste',
    starred_url: 'teste',
    subscriptions_url: 'teste',
    organizations_url: 'teste',
    repos_url: 'teste',
    events_url: 'teste',
    received_events_url: 'teste',
    type: 'teste',
    site_admin: true,
    score: 0
}

export const UserSearchMock: UserSearch = {
    total_count: 0,
    incomplete_results: false,
    items: [GithubUserMock]
}

export const DetailedUserSearchMock = {
    login: 'teste',
    id: 0,
    node_id: 'teste',
    avatar_url: 'https://avatars.githubusercontent.com/u/70849974?v=4',
    gravatar_id: 'teste',
    url: 'teste',
    html_url: 'teste',
    followers_url: 'teste',
    following_url: 'teste',
    gists_url: 'teste',
    starred_url: 'teste',
    subscriptions_url: 'teste',
    organizations_url: 'teste',
    repos_url: 'teste',
    events_url: 'teste',
    received_events_url: 'teste',
    type: 'teste',
    site_admin: true,
    name: 'teste',
    company: 'teste',
    blog: 'teste',
    location: 'teste',
    email: 'teste',
    hireable: 'teste',
    bio: 'teste',
    twitter_username: 'teste',
    public_repos: 0,
    public_gists: 0,
    followers: 0,
    following: 0,
    created_at: 'teste',
    updated_at: 'teste'
}

export const RepoSearchMock: RepoSearch = {
    id: 0,
    node_id: 'teste',
    name: 'Repo name',
    full_name: 'Repo full name',
    private: false,
    owner: {
      login: 'theone',
      id: 0,
      node_id: 'teste',
      avatar_url: 'https://avatars.githubusercontent.com/u/70849974?v=4',
      gravatar_id: 'teste',
      url: 'teste',
      html_url: 'teste',
      followers_url: 'teste',
      following_url: 'teste',
      gists_url: 'teste',
      starred_url: 'teste',
      subscriptions_url: 'teste',
      organizations_url: 'teste',
      repos_url: 'teste',
      events_url: 'teste',
      received_events_url: 'teste',
      type: 'teste',
      site_admin: false
    },
    html_url: 'teste',
    description: 'this is a mocked repo description',
    fork: true,
    url: 'teste',
    forks_url: 'teste',
    keys_url: 'teste',
    collaborators_url: 'teste',
    teams_url: 'teste',
    hooks_url: 'teste',
    issue_events_url: 'teste',
    events_url: 'teste',
    assignees_url: 'teste',
    branches_url: 'teste',
    tags_url: 'teste',
    blobs_url: 'teste',
    git_tags_url: 'teste',
    git_refs_url: 'teste',
    trees_url: 'teste',
    statuses_url: 'teste',
    languages_url: 'teste',
    stargazers_url: 'teste',
    contributors_url: 'teste',
    subscribers_url: 'teste',
    subscription_url: 'teste',
    commits_url: 'teste',
    git_commits_url: 'teste',
    comments_url: 'teste',
    issue_comment_url: 'teste',
    contents_url: 'teste',
    compare_url: 'teste',
    merges_url: 'teste',
    archive_url: 'teste',
    downloads_url: 'teste',
    issues_url: 'teste',
    pulls_url: 'teste',
    milestones_url: 'teste',
    notifications_url: 'teste',
    labels_url: 'teste',
    releases_url: 'teste',
    deployments_url: 'teste',
    created_at: 'teste',
    updated_at: 'teste',
    pushed_at: 'teste',
    git_url: 'teste',
    ssh_url: 'teste',
    clone_url: 'teste',
    svn_url: 'teste',
    homepage: 'teste',
    size: 0,
    stargazers_count: 0,
    watchers_count: 0,
    language: 'typescript',
    has_issues: true,
    has_projects: true,
    has_downloads: true,
    has_wiki: true,
    has_pages: true,
    has_discussions: true,
    forks_count: 0,
    mirror_url: 'teste',
    archived: true,
    disabled: true,
    open_issues_count: 0,
    license: 'teste',
    allow_forking: true,
    is_template: true,
    web_commit_signoff_required: true,
    topics: [],
    visibility: 'teste',
    forks: 0,
    open_issues: 0,
    watchers: 0,
    default_branch: 'teste'
  }